//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace BLL.serviceDieuPhoi {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WS_DieuPhoiSoap", Namespace="http://tempuri.org/")]
    public partial class WS_DieuPhoi : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback FindAllOperationCompleted;
        
        private System.Threading.SendOrPostCallback FindOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WS_DieuPhoi() {
            this.Url = global::BLL.Properties.Settings.Default.BLL_serviceDieuPhoi_WS_DieuPhoi;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event FindAllCompletedEventHandler FindAllCompleted;
        
        /// <remarks/>
        public event FindCompletedEventHandler FindCompleted;
        
        /// <remarks/>
        public event AddCompletedEventHandler AddCompleted;
        
        /// <remarks/>
        public event DeleteCompletedEventHandler DeleteCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/FindAll", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DIEUPHOI[] FindAll() {
            object[] results = this.Invoke("FindAll", new object[0]);
            return ((DIEUPHOI[])(results[0]));
        }
        
        /// <remarks/>
        public void FindAllAsync() {
            this.FindAllAsync(null);
        }
        
        /// <remarks/>
        public void FindAllAsync(object userState) {
            if ((this.FindAllOperationCompleted == null)) {
                this.FindAllOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFindAllOperationCompleted);
            }
            this.InvokeAsync("FindAll", new object[0], this.FindAllOperationCompleted, userState);
        }
        
        private void OnFindAllOperationCompleted(object arg) {
            if ((this.FindAllCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FindAllCompleted(this, new FindAllCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Find", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DIEUPHOI[] Find(string MaCS) {
            object[] results = this.Invoke("Find", new object[] {
                        MaCS});
            return ((DIEUPHOI[])(results[0]));
        }
        
        /// <remarks/>
        public void FindAsync(string MaCS) {
            this.FindAsync(MaCS, null);
        }
        
        /// <remarks/>
        public void FindAsync(string MaCS, object userState) {
            if ((this.FindOperationCompleted == null)) {
                this.FindOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFindOperationCompleted);
            }
            this.InvokeAsync("Find", new object[] {
                        MaCS}, this.FindOperationCompleted, userState);
        }
        
        private void OnFindOperationCompleted(object arg) {
            if ((this.FindCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FindCompleted(this, new FindCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Add", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Add(string MaCS, string MaHoaDon) {
            object[] results = this.Invoke("Add", new object[] {
                        MaCS,
                        MaHoaDon});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void AddAsync(string MaCS, string MaHoaDon) {
            this.AddAsync(MaCS, MaHoaDon, null);
        }
        
        /// <remarks/>
        public void AddAsync(string MaCS, string MaHoaDon, object userState) {
            if ((this.AddOperationCompleted == null)) {
                this.AddOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddOperationCompleted);
            }
            this.InvokeAsync("Add", new object[] {
                        MaCS,
                        MaHoaDon}, this.AddOperationCompleted, userState);
        }
        
        private void OnAddOperationCompleted(object arg) {
            if ((this.AddCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddCompleted(this, new AddCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Delete", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Delete(string MaCS, string MaHoaDon) {
            object[] results = this.Invoke("Delete", new object[] {
                        MaCS,
                        MaHoaDon});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteAsync(string MaCS, string MaHoaDon) {
            this.DeleteAsync(MaCS, MaHoaDon, null);
        }
        
        /// <remarks/>
        public void DeleteAsync(string MaCS, string MaHoaDon, object userState) {
            if ((this.DeleteOperationCompleted == null)) {
                this.DeleteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteOperationCompleted);
            }
            this.InvokeAsync("Delete", new object[] {
                        MaCS,
                        MaHoaDon}, this.DeleteOperationCompleted, userState);
        }
        
        private void OnDeleteOperationCompleted(object arg) {
            if ((this.DeleteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteCompleted(this, new DeleteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class DIEUPHOI {
        
        private string mACSField;
        
        private string mAHOADONField;
        
        private COSO cOSOField;
        
        private HOADON hOADONField;
        
        /// <remarks/>
        public string MACS {
            get {
                return this.mACSField;
            }
            set {
                this.mACSField = value;
            }
        }
        
        /// <remarks/>
        public string MAHOADON {
            get {
                return this.mAHOADONField;
            }
            set {
                this.mAHOADONField = value;
            }
        }
        
        /// <remarks/>
        public COSO COSO {
            get {
                return this.cOSOField;
            }
            set {
                this.cOSOField = value;
            }
        }
        
        /// <remarks/>
        public HOADON HOADON {
            get {
                return this.hOADONField;
            }
            set {
                this.hOADONField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class COSO {
        
        private string mACSField;
        
        private string tENCSField;
        
        private string dIACHIField;
        
        private string sDTField;
        
        private string hinhAnhField;
        
        /// <remarks/>
        public string MACS {
            get {
                return this.mACSField;
            }
            set {
                this.mACSField = value;
            }
        }
        
        /// <remarks/>
        public string TENCS {
            get {
                return this.tENCSField;
            }
            set {
                this.tENCSField = value;
            }
        }
        
        /// <remarks/>
        public string DIACHI {
            get {
                return this.dIACHIField;
            }
            set {
                this.dIACHIField = value;
            }
        }
        
        /// <remarks/>
        public string SDT {
            get {
                return this.sDTField;
            }
            set {
                this.sDTField = value;
            }
        }
        
        /// <remarks/>
        public string HinhAnh {
            get {
                return this.hinhAnhField;
            }
            set {
                this.hinhAnhField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class LOAINHANVIEN {
        
        private string mALOAINVField;
        
        private string tENLOAINVField;
        
        /// <remarks/>
        public string MALOAINV {
            get {
                return this.mALOAINVField;
            }
            set {
                this.mALOAINVField = value;
            }
        }
        
        /// <remarks/>
        public string TENLOAINV {
            get {
                return this.tENLOAINVField;
            }
            set {
                this.tENLOAINVField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class NHANVIEN {
        
        private string mANVField;
        
        private string mALOAINVField;
        
        private string mACSField;
        
        private string hOTENNVField;
        
        private string sDT_NVField;
        
        private string cMNDField;
        
        private string eMAILField;
        
        private string dIACHI_NVField;
        
        private string mATKHAUField;
        
        private COSO cOSOField;
        
        private LOAINHANVIEN lOAINHANVIENField;
        
        /// <remarks/>
        public string MANV {
            get {
                return this.mANVField;
            }
            set {
                this.mANVField = value;
            }
        }
        
        /// <remarks/>
        public string MALOAINV {
            get {
                return this.mALOAINVField;
            }
            set {
                this.mALOAINVField = value;
            }
        }
        
        /// <remarks/>
        public string MACS {
            get {
                return this.mACSField;
            }
            set {
                this.mACSField = value;
            }
        }
        
        /// <remarks/>
        public string HOTENNV {
            get {
                return this.hOTENNVField;
            }
            set {
                this.hOTENNVField = value;
            }
        }
        
        /// <remarks/>
        public string SDT_NV {
            get {
                return this.sDT_NVField;
            }
            set {
                this.sDT_NVField = value;
            }
        }
        
        /// <remarks/>
        public string CMND {
            get {
                return this.cMNDField;
            }
            set {
                this.cMNDField = value;
            }
        }
        
        /// <remarks/>
        public string EMAIL {
            get {
                return this.eMAILField;
            }
            set {
                this.eMAILField = value;
            }
        }
        
        /// <remarks/>
        public string DIACHI_NV {
            get {
                return this.dIACHI_NVField;
            }
            set {
                this.dIACHI_NVField = value;
            }
        }
        
        /// <remarks/>
        public string MATKHAU {
            get {
                return this.mATKHAUField;
            }
            set {
                this.mATKHAUField = value;
            }
        }
        
        /// <remarks/>
        public COSO COSO {
            get {
                return this.cOSOField;
            }
            set {
                this.cOSOField = value;
            }
        }
        
        /// <remarks/>
        public LOAINHANVIEN LOAINHANVIEN {
            get {
                return this.lOAINHANVIENField;
            }
            set {
                this.lOAINHANVIENField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class KHACHHANG {
        
        private string hOTENKHField;
        
        private string sDTField;
        
        private string eMAILField;
        
        private System.Nullable<int> dIEMTICHField;
        
        private string hinhAnhField;
        
        /// <remarks/>
        public string HOTENKH {
            get {
                return this.hOTENKHField;
            }
            set {
                this.hOTENKHField = value;
            }
        }
        
        /// <remarks/>
        public string SDT {
            get {
                return this.sDTField;
            }
            set {
                this.sDTField = value;
            }
        }
        
        /// <remarks/>
        public string EMAIL {
            get {
                return this.eMAILField;
            }
            set {
                this.eMAILField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> DIEMTICH {
            get {
                return this.dIEMTICHField;
            }
            set {
                this.dIEMTICHField = value;
            }
        }
        
        /// <remarks/>
        public string HinhAnh {
            get {
                return this.hinhAnhField;
            }
            set {
                this.hinhAnhField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class HOADON {
        
        private string mAHOADONField;
        
        private string mANVField;
        
        private string sDT_KHField;
        
        private System.Nullable<System.DateTime> nGAYGIOLAPField;
        
        private System.Nullable<decimal> tHANHTIENField;
        
        private string tRANGTHAIField;
        
        private string dIACHIField;
        
        private string lOAIHDField;
        
        private KHACHHANG kHACHHANGField;
        
        private NHANVIEN nHANVIENField;
        
        /// <remarks/>
        public string MAHOADON {
            get {
                return this.mAHOADONField;
            }
            set {
                this.mAHOADONField = value;
            }
        }
        
        /// <remarks/>
        public string MANV {
            get {
                return this.mANVField;
            }
            set {
                this.mANVField = value;
            }
        }
        
        /// <remarks/>
        public string SDT_KH {
            get {
                return this.sDT_KHField;
            }
            set {
                this.sDT_KHField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> NGAYGIOLAP {
            get {
                return this.nGAYGIOLAPField;
            }
            set {
                this.nGAYGIOLAPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> THANHTIEN {
            get {
                return this.tHANHTIENField;
            }
            set {
                this.tHANHTIENField = value;
            }
        }
        
        /// <remarks/>
        public string TRANGTHAI {
            get {
                return this.tRANGTHAIField;
            }
            set {
                this.tRANGTHAIField = value;
            }
        }
        
        /// <remarks/>
        public string DIACHI {
            get {
                return this.dIACHIField;
            }
            set {
                this.dIACHIField = value;
            }
        }
        
        /// <remarks/>
        public string LOAIHD {
            get {
                return this.lOAIHDField;
            }
            set {
                this.lOAIHDField = value;
            }
        }
        
        /// <remarks/>
        public KHACHHANG KHACHHANG {
            get {
                return this.kHACHHANGField;
            }
            set {
                this.kHACHHANGField = value;
            }
        }
        
        /// <remarks/>
        public NHANVIEN NHANVIEN {
            get {
                return this.nHANVIENField;
            }
            set {
                this.nHANVIENField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void FindAllCompletedEventHandler(object sender, FindAllCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FindAllCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FindAllCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DIEUPHOI[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DIEUPHOI[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void FindCompletedEventHandler(object sender, FindCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FindCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FindCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DIEUPHOI[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DIEUPHOI[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void AddCompletedEventHandler(object sender, AddCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void DeleteCompletedEventHandler(object sender, DeleteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591