//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace BLL.serviceChiTietHoaDon {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WS_ChiTietHoaDonSoap", Namespace="http://tempuri.org/")]
    public partial class WS_ChiTietHoaDon : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback AddOperationCompleted;
        
        private System.Threading.SendOrPostCallback FindAllOperationCompleted;
        
        private System.Threading.SendOrPostCallback FindOperationCompleted;
        
        private System.Threading.SendOrPostCallback FindByMaHDOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WS_ChiTietHoaDon() {
            this.Url = global::BLL.Properties.Settings.Default.BLL_serviceChiTietHoaDon_WS_ChiTietHoaDon;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event AddCompletedEventHandler AddCompleted;
        
        /// <remarks/>
        public event FindAllCompletedEventHandler FindAllCompleted;
        
        /// <remarks/>
        public event FindCompletedEventHandler FindCompleted;
        
        /// <remarks/>
        public event FindByMaHDCompletedEventHandler FindByMaHDCompleted;
        
        /// <remarks/>
        public event DeleteCompletedEventHandler DeleteCompleted;
        
        /// <remarks/>
        public event UpdateCompletedEventHandler UpdateCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Add", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Add(string MaHoaDon, string MaSP, int SL_SP) {
            object[] results = this.Invoke("Add", new object[] {
                        MaHoaDon,
                        MaSP,
                        SL_SP});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void AddAsync(string MaHoaDon, string MaSP, int SL_SP) {
            this.AddAsync(MaHoaDon, MaSP, SL_SP, null);
        }
        
        /// <remarks/>
        public void AddAsync(string MaHoaDon, string MaSP, int SL_SP, object userState) {
            if ((this.AddOperationCompleted == null)) {
                this.AddOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddOperationCompleted);
            }
            this.InvokeAsync("Add", new object[] {
                        MaHoaDon,
                        MaSP,
                        SL_SP}, this.AddOperationCompleted, userState);
        }
        
        private void OnAddOperationCompleted(object arg) {
            if ((this.AddCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddCompleted(this, new AddCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/FindAll", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CHITIETHOADON[] FindAll() {
            object[] results = this.Invoke("FindAll", new object[0]);
            return ((CHITIETHOADON[])(results[0]));
        }
        
        /// <remarks/>
        public void FindAllAsync() {
            this.FindAllAsync(null);
        }
        
        /// <remarks/>
        public void FindAllAsync(object userState) {
            if ((this.FindAllOperationCompleted == null)) {
                this.FindAllOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFindAllOperationCompleted);
            }
            this.InvokeAsync("FindAll", new object[0], this.FindAllOperationCompleted, userState);
        }
        
        private void OnFindAllOperationCompleted(object arg) {
            if ((this.FindAllCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FindAllCompleted(this, new FindAllCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Find", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CHITIETHOADON Find(string MaHoaDon, string MaSP) {
            object[] results = this.Invoke("Find", new object[] {
                        MaHoaDon,
                        MaSP});
            return ((CHITIETHOADON)(results[0]));
        }
        
        /// <remarks/>
        public void FindAsync(string MaHoaDon, string MaSP) {
            this.FindAsync(MaHoaDon, MaSP, null);
        }
        
        /// <remarks/>
        public void FindAsync(string MaHoaDon, string MaSP, object userState) {
            if ((this.FindOperationCompleted == null)) {
                this.FindOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFindOperationCompleted);
            }
            this.InvokeAsync("Find", new object[] {
                        MaHoaDon,
                        MaSP}, this.FindOperationCompleted, userState);
        }
        
        private void OnFindOperationCompleted(object arg) {
            if ((this.FindCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FindCompleted(this, new FindCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/FindByMaHD", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CHITIETHOADON[] FindByMaHD(string MaHoaDon) {
            object[] results = this.Invoke("FindByMaHD", new object[] {
                        MaHoaDon});
            return ((CHITIETHOADON[])(results[0]));
        }
        
        /// <remarks/>
        public void FindByMaHDAsync(string MaHoaDon) {
            this.FindByMaHDAsync(MaHoaDon, null);
        }
        
        /// <remarks/>
        public void FindByMaHDAsync(string MaHoaDon, object userState) {
            if ((this.FindByMaHDOperationCompleted == null)) {
                this.FindByMaHDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFindByMaHDOperationCompleted);
            }
            this.InvokeAsync("FindByMaHD", new object[] {
                        MaHoaDon}, this.FindByMaHDOperationCompleted, userState);
        }
        
        private void OnFindByMaHDOperationCompleted(object arg) {
            if ((this.FindByMaHDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FindByMaHDCompleted(this, new FindByMaHDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Delete", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Delete(string MaHoaDon, string MaSP) {
            object[] results = this.Invoke("Delete", new object[] {
                        MaHoaDon,
                        MaSP});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteAsync(string MaHoaDon, string MaSP) {
            this.DeleteAsync(MaHoaDon, MaSP, null);
        }
        
        /// <remarks/>
        public void DeleteAsync(string MaHoaDon, string MaSP, object userState) {
            if ((this.DeleteOperationCompleted == null)) {
                this.DeleteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteOperationCompleted);
            }
            this.InvokeAsync("Delete", new object[] {
                        MaHoaDon,
                        MaSP}, this.DeleteOperationCompleted, userState);
        }
        
        private void OnDeleteOperationCompleted(object arg) {
            if ((this.DeleteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteCompleted(this, new DeleteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Update", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Update(string MaHoaDon, string MaSP, int SL_SP) {
            object[] results = this.Invoke("Update", new object[] {
                        MaHoaDon,
                        MaSP,
                        SL_SP});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateAsync(string MaHoaDon, string MaSP, int SL_SP) {
            this.UpdateAsync(MaHoaDon, MaSP, SL_SP, null);
        }
        
        /// <remarks/>
        public void UpdateAsync(string MaHoaDon, string MaSP, int SL_SP, object userState) {
            if ((this.UpdateOperationCompleted == null)) {
                this.UpdateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateOperationCompleted);
            }
            this.InvokeAsync("Update", new object[] {
                        MaHoaDon,
                        MaSP,
                        SL_SP}, this.UpdateOperationCompleted, userState);
        }
        
        private void OnUpdateOperationCompleted(object arg) {
            if ((this.UpdateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateCompleted(this, new UpdateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CHITIETHOADON {
        
        private string mAHOADONField;
        
        private string mASPField;
        
        private System.Nullable<int> sL_SPField;
        
        private HOADON hOADONField;
        
        private SANPHAM sANPHAMField;
        
        /// <remarks/>
        public string MAHOADON {
            get {
                return this.mAHOADONField;
            }
            set {
                this.mAHOADONField = value;
            }
        }
        
        /// <remarks/>
        public string MASP {
            get {
                return this.mASPField;
            }
            set {
                this.mASPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> SL_SP {
            get {
                return this.sL_SPField;
            }
            set {
                this.sL_SPField = value;
            }
        }
        
        /// <remarks/>
        public HOADON HOADON {
            get {
                return this.hOADONField;
            }
            set {
                this.hOADONField = value;
            }
        }
        
        /// <remarks/>
        public SANPHAM SANPHAM {
            get {
                return this.sANPHAMField;
            }
            set {
                this.sANPHAMField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class HOADON {
        
        private string mAHOADONField;
        
        private string mANVField;
        
        private string sDT_KHField;
        
        private System.Nullable<System.DateTime> nGAYGIOLAPField;
        
        private System.Nullable<decimal> tHANHTIENField;
        
        private string tRANGTHAIField;
        
        private string dIACHIField;
        
        private string lOAIHDField;
        
        private KHACHHANG kHACHHANGField;
        
        private NHANVIEN nHANVIENField;
        
        /// <remarks/>
        public string MAHOADON {
            get {
                return this.mAHOADONField;
            }
            set {
                this.mAHOADONField = value;
            }
        }
        
        /// <remarks/>
        public string MANV {
            get {
                return this.mANVField;
            }
            set {
                this.mANVField = value;
            }
        }
        
        /// <remarks/>
        public string SDT_KH {
            get {
                return this.sDT_KHField;
            }
            set {
                this.sDT_KHField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> NGAYGIOLAP {
            get {
                return this.nGAYGIOLAPField;
            }
            set {
                this.nGAYGIOLAPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> THANHTIEN {
            get {
                return this.tHANHTIENField;
            }
            set {
                this.tHANHTIENField = value;
            }
        }
        
        /// <remarks/>
        public string TRANGTHAI {
            get {
                return this.tRANGTHAIField;
            }
            set {
                this.tRANGTHAIField = value;
            }
        }
        
        /// <remarks/>
        public string DIACHI {
            get {
                return this.dIACHIField;
            }
            set {
                this.dIACHIField = value;
            }
        }
        
        /// <remarks/>
        public string LOAIHD {
            get {
                return this.lOAIHDField;
            }
            set {
                this.lOAIHDField = value;
            }
        }
        
        /// <remarks/>
        public KHACHHANG KHACHHANG {
            get {
                return this.kHACHHANGField;
            }
            set {
                this.kHACHHANGField = value;
            }
        }
        
        /// <remarks/>
        public NHANVIEN NHANVIEN {
            get {
                return this.nHANVIENField;
            }
            set {
                this.nHANVIENField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class KHACHHANG {
        
        private string hOTENKHField;
        
        private string sDTField;
        
        private string eMAILField;
        
        private System.Nullable<int> dIEMTICHField;
        
        private string hinhAnhField;
        
        /// <remarks/>
        public string HOTENKH {
            get {
                return this.hOTENKHField;
            }
            set {
                this.hOTENKHField = value;
            }
        }
        
        /// <remarks/>
        public string SDT {
            get {
                return this.sDTField;
            }
            set {
                this.sDTField = value;
            }
        }
        
        /// <remarks/>
        public string EMAIL {
            get {
                return this.eMAILField;
            }
            set {
                this.eMAILField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> DIEMTICH {
            get {
                return this.dIEMTICHField;
            }
            set {
                this.dIEMTICHField = value;
            }
        }
        
        /// <remarks/>
        public string HinhAnh {
            get {
                return this.hinhAnhField;
            }
            set {
                this.hinhAnhField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class LOAISP {
        
        private string mALOAISPField;
        
        private string tENLOAISPField;
        
        private string hinhAnhField;
        
        /// <remarks/>
        public string MALOAISP {
            get {
                return this.mALOAISPField;
            }
            set {
                this.mALOAISPField = value;
            }
        }
        
        /// <remarks/>
        public string TENLOAISP {
            get {
                return this.tENLOAISPField;
            }
            set {
                this.tENLOAISPField = value;
            }
        }
        
        /// <remarks/>
        public string HinhAnh {
            get {
                return this.hinhAnhField;
            }
            set {
                this.hinhAnhField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SANPHAM {
        
        private string mASPField;
        
        private string mALOAISPField;
        
        private string tENSPField;
        
        private System.Nullable<int> dONGIAField;
        
        private string hinhAnhField;
        
        private LOAISP lOAISPField;
        
        /// <remarks/>
        public string MASP {
            get {
                return this.mASPField;
            }
            set {
                this.mASPField = value;
            }
        }
        
        /// <remarks/>
        public string MALOAISP {
            get {
                return this.mALOAISPField;
            }
            set {
                this.mALOAISPField = value;
            }
        }
        
        /// <remarks/>
        public string TENSP {
            get {
                return this.tENSPField;
            }
            set {
                this.tENSPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> DONGIA {
            get {
                return this.dONGIAField;
            }
            set {
                this.dONGIAField = value;
            }
        }
        
        /// <remarks/>
        public string HinhAnh {
            get {
                return this.hinhAnhField;
            }
            set {
                this.hinhAnhField = value;
            }
        }
        
        /// <remarks/>
        public LOAISP LOAISP {
            get {
                return this.lOAISPField;
            }
            set {
                this.lOAISPField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class LOAINHANVIEN {
        
        private string mALOAINVField;
        
        private string tENLOAINVField;
        
        /// <remarks/>
        public string MALOAINV {
            get {
                return this.mALOAINVField;
            }
            set {
                this.mALOAINVField = value;
            }
        }
        
        /// <remarks/>
        public string TENLOAINV {
            get {
                return this.tENLOAINVField;
            }
            set {
                this.tENLOAINVField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class COSO {
        
        private string mACSField;
        
        private string tENCSField;
        
        private string dIACHIField;
        
        private string sDTField;
        
        private string hinhAnhField;
        
        /// <remarks/>
        public string MACS {
            get {
                return this.mACSField;
            }
            set {
                this.mACSField = value;
            }
        }
        
        /// <remarks/>
        public string TENCS {
            get {
                return this.tENCSField;
            }
            set {
                this.tENCSField = value;
            }
        }
        
        /// <remarks/>
        public string DIACHI {
            get {
                return this.dIACHIField;
            }
            set {
                this.dIACHIField = value;
            }
        }
        
        /// <remarks/>
        public string SDT {
            get {
                return this.sDTField;
            }
            set {
                this.sDTField = value;
            }
        }
        
        /// <remarks/>
        public string HinhAnh {
            get {
                return this.hinhAnhField;
            }
            set {
                this.hinhAnhField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class NHANVIEN {
        
        private string mANVField;
        
        private string mALOAINVField;
        
        private string mACSField;
        
        private string hOTENNVField;
        
        private string sDT_NVField;
        
        private string cMNDField;
        
        private string eMAILField;
        
        private string dIACHI_NVField;
        
        private string mATKHAUField;
        
        private COSO cOSOField;
        
        private LOAINHANVIEN lOAINHANVIENField;
        
        /// <remarks/>
        public string MANV {
            get {
                return this.mANVField;
            }
            set {
                this.mANVField = value;
            }
        }
        
        /// <remarks/>
        public string MALOAINV {
            get {
                return this.mALOAINVField;
            }
            set {
                this.mALOAINVField = value;
            }
        }
        
        /// <remarks/>
        public string MACS {
            get {
                return this.mACSField;
            }
            set {
                this.mACSField = value;
            }
        }
        
        /// <remarks/>
        public string HOTENNV {
            get {
                return this.hOTENNVField;
            }
            set {
                this.hOTENNVField = value;
            }
        }
        
        /// <remarks/>
        public string SDT_NV {
            get {
                return this.sDT_NVField;
            }
            set {
                this.sDT_NVField = value;
            }
        }
        
        /// <remarks/>
        public string CMND {
            get {
                return this.cMNDField;
            }
            set {
                this.cMNDField = value;
            }
        }
        
        /// <remarks/>
        public string EMAIL {
            get {
                return this.eMAILField;
            }
            set {
                this.eMAILField = value;
            }
        }
        
        /// <remarks/>
        public string DIACHI_NV {
            get {
                return this.dIACHI_NVField;
            }
            set {
                this.dIACHI_NVField = value;
            }
        }
        
        /// <remarks/>
        public string MATKHAU {
            get {
                return this.mATKHAUField;
            }
            set {
                this.mATKHAUField = value;
            }
        }
        
        /// <remarks/>
        public COSO COSO {
            get {
                return this.cOSOField;
            }
            set {
                this.cOSOField = value;
            }
        }
        
        /// <remarks/>
        public LOAINHANVIEN LOAINHANVIEN {
            get {
                return this.lOAINHANVIENField;
            }
            set {
                this.lOAINHANVIENField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void AddCompletedEventHandler(object sender, AddCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void FindAllCompletedEventHandler(object sender, FindAllCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FindAllCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FindAllCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CHITIETHOADON[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CHITIETHOADON[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void FindCompletedEventHandler(object sender, FindCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FindCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FindCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CHITIETHOADON Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CHITIETHOADON)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void FindByMaHDCompletedEventHandler(object sender, FindByMaHDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FindByMaHDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FindByMaHDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CHITIETHOADON[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CHITIETHOADON[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void DeleteCompletedEventHandler(object sender, DeleteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void UpdateCompletedEventHandler(object sender, UpdateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591